namespace Euler

//Each new term in the Fibonacci sequence 
// is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence 
// whose values do not exceed four million, 
// find the sum of the even-valued terms.

module EcersiseOne=
  let fibonacciEvenSum limit =
    let rec fibonacciHelper a b sum =
        if b > limit then
            sum
        else
            let next = a + b
            let evenSum = if b % 2 = 0 then sum + b else sum
            fibonacciHelper b next evenSum

    fibonacciHelper 1 2 0

  let result = fibonacciEvenSum 4000000
  printfn "The sum of even-valued Fibonacci terms not exceeding 4 million is %d" result


    
